rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/Cinema?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    password: password
  flyway:
    enabled: false

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate-ddl-auto: update

  sql:
    init:
      mode: always


